export const JOB_STATES = [
  'RECEIVED',
  'VALIDATING',
  'CHECKING_JELLYFIN',
  'CHECKING_SEERR_OWNERSHIP',
  'RESOLVING_QUALITY_PROFILE',
  'SEARCHING_XTREAM',
  'EVALUATING_XTREAM_CANDIDATES',
  'XTREAM_MATCHED',
  'XTREAM_NOT_FOUND',
  'XTREAM_AMBIGUOUS',
  'XTREAM_QUEUING',
  'XTREAM_QUEUED',
  'XTREAM_DOWNLOADING',
  'WAITING_FOR_JELLYFIN',
  'AVAILABLE',
  'COMPLETING_SEERR',
  'COMPLETED',
  'FALLBACK_PENDING',
  'FALLBACK_APPROVING',
  'HANDED_TO_ARR',
  'EXTERNALLY_HANDLED',
  'FAILED_RETRYABLE',
  'FAILED_PERMANENT',
] as const;

export type JobState = (typeof JOB_STATES)[number];

export const TERMINAL_STATES: ReadonlySet<JobState> = new Set([
  'COMPLETED',
  'HANDED_TO_ARR',
  'EXTERNALLY_HANDLED',
  'FAILED_PERMANENT',
]);

export function isTerminalState(state: JobState): boolean {
  return TERMINAL_STATES.has(state);
}
